### ISSUE TITLE
Repository Naming

### ISSUE THREAD

**Issue by Gary050613** [andyzhu23/Competitive-Programming#1]
Hi Mr. andyzhu23,

Currently, the name of your repository is "Competitve-Programming", but according to my research and my knowledge and multiple sources including Merriam-webster dictionary, the spelling of "Competitve" is actually COMPETITIVE! WTIH AN I!!! Ur welcome 😄 

Sincerely,
Gary050613

**Comment by andyzhu23** [comment]
Hi Gary050613,

I can name my repository anything, it is a free country,

Kind Regards,

andyzhu23

**Comment by Gary050613** [comment]
Sir, we are international.
Pls change. My OCD is killing me.

Thanks,
Gary050613

**Comment by andyzhu23** [comment]
Dear Gary050613,

nah, I can't spell.

Best Regards

andyzhu23
